### ISSUE TITLE
wkt-wickedcharts: NPE when invalid data is provided

### ISSUE THREAD

**Issue by danhaywood** [incodehq/incode-platform#29]
from https://github.com/isisaddons-legacy/isis-wicket-wickedcharts/issues/2

With the current Java Math demo data in the KitchenSink application trying to show a `summarychart` leads to the following exception:

```
Caused by: java.lang.NullPointerException
    at java.math.BigDecimal.compareTo(BigDecimal.java:2554)
    at java.math.BigDecimal.min(BigDecimal.java:2665)
    at org.isisaddons.wicket.wickedcharts.cpt.ui.summarychart.CollectionContentsAsSummaryChart.minOf(CollectionContentsAsSummaryChart.java:163)
    at org.isisaddons.wicket.wickedcharts.cpt.ui.summarychart.CollectionContentsAsSummaryChart.createChartValue(CollectionContentsAsSummaryChart.java:119)
    at org.isisaddons.wicket.wickedcharts.cpt.ui.summarychart.CollectionContentsAsSummaryChart.buildGui(CollectionContentsAsSummaryChart.java:101)
    at org.isisaddons.wicket.wickedcharts.cpt.ui.summarychart.CollectionContentsAsSummaryChart.onModelChanged(CollectionContentsAsSummaryChart.java:168)
```

**Comment by danhaywood** [comment]
I use the following fix locally to avoid the NPE. Not sure it is the correct one though

``` diff
     private BigDecimal maxOf(BigDecimal max, final BigDecimal summaryMax) {
-        return max != null ? max.max(summaryMax) : summaryMax;
+        return max != null
+            ? summaryMax != null
+                ? max.max(summaryMax)
+                : max
+            : BigDecimal.ZERO;
     }

     private BigDecimal minOf(BigDecimal min, final BigDecimal summaryMin) {
-        return min != null ? min.min(summaryMin) : summaryMin;
+        return min != null
+            ? summaryMin != null
+                ? min.min(summaryMin)
+                : min
+            : BigDecimal.ZERO;
     }
```

**Comment by danhaywood** [comment]
danhaywood:

possibly not; what if every value is null?  The result ought to be null,
but I think this code might give BigDecimal.ZERO.

**Comment by danhaywood** [comment]
martin-g:

returning `null` instead of `BigDecimal.ZERO` seems to do the job as well
